# Generated by Django 4.2 on 2023-05-24 11:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fio', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.IntegerField(null=True)),
                ('state', models.CharField(blank=True, choices=[('AP', 'Одобрить'), ('RJ', 'Отклонить'), ('PR', 'На рассмотрении')], default='PR', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Активные заявления',
                'verbose_name_plural': 'Активные заявления',
            },
        ),
        migrations.CreateModel(
            name='ApplicationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fio', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Архив заявлений',
                'verbose_name_plural': 'Архив заявлений',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('fio', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sum', models.IntegerField(null=True)),
                ('state', models.CharField(blank=True, default='Ожидает выплаты', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявления к выплате',
                'verbose_name_plural': 'Заявления к выплате',
            },
        ),
        migrations.CreateModel(
            name='BenefitImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('benefit', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.department', verbose_name='Подотдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдел',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='PaidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('fio', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Выплаченные заявления',
                'verbose_name_plural': 'Выплаченные заявления',
            },
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('user_fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('access', models.CharField(max_length=1, null=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Неподтверждённые пользователи',
                'verbose_name_plural': 'Неподтверждённые пользователи',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('user_fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('pin_code', models.IntegerField(max_length=30, null=True, verbose_name='Код доступа к боту')),
                ('sex', models.CharField(blank=True, choices=[('M', 'М'), ('F', 'Ж')], max_length=1, verbose_name='Пол')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('dateOfHiring', models.DateField(null=True, verbose_name='Дата приёма на работу')),
                ('balance', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Баланс')),
                ('wood_coins', models.IntegerField(blank=True, editable=False, null=True, verbose_name='WoodCoins')),
                ('staff_type', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                ('access', models.CharField(choices=[('A', 'Подтверждено'), ('P', 'На рассмотрении')], default='P', max_length=1, null=True, verbose_name='Доступ')),
                ('fired', models.BooleanField(default=False, verbose_name='Уволен')),
                ('department', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='main.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('user_fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('department', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to='main.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='DocumentsInApplicationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationarchive')),
                ('document', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.document')),
            ],
            options={
                'verbose_name': 'Пакет документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentsInApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activeapplication')),
                ('document', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.document')),
            ],
            options={
                'verbose_name': 'Пакет документов',
            },
        ),
    ]
