# Generated by Django 4.2 on 2023-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(null=True, verbose_name='Код доступа к боту'),
        ),
    ]
