# Generated by Django 4.2 on 2023-05-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
