# Generated by Django 4.2 on 2023-05-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_department_user_department_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='department',
            new_name='department_sup',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='user_fio',
            new_name='sup_fio',
        ),
        migrations.RemoveField(
            model_name='department',
            name='supervisor_dep',
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supervisor', verbose_name='Руководитель'),
        ),
    ]
